name: App Engine Staging Deployment
on:
  push:
    # FIXME: Uncomment the `branches` line before submitting.
    # It is needed as a comment for me to test this.
    # Master branch has the staging firebase config.
    # branches: [ master ]
    paths:
      - '.github/workflows/**'
      - 'api/**'
      - 'server/**'
      - 'client/flutter/assets/content_bundles/**'
      - 'content/**'

jobs:
  deploy_to_appengine_staging:
    name: Deploy Server to App Engine (Staging)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12.0.2'
          architecture: x86
      - uses: GoogleCloudPlatform/github-actions/setup-gcloud@0.1.2
        with:
          project_id: who-myhealth-staging
      - run: gcloud info
      - name: Setup GCP Credentials
        shell: bash
        run: |
          echo "$BASE64_KEY_JSON" | base64 --decode > $APPLICATION_CREDENTIALS_GPG
          gpg --quiet --batch --yes --decrypt --passphrase="$KEY_PASSPHRASE" --output $APPLICATION_CREDENTIALS $APPLICATION_CREDENTIALS_GPG
          rm $PPLICATION_CREDENTIALS_GPG
          gcloud auth activate-service-account --key-file=$APPLICATION_CREDENTIALS
        env:
          BASE64_KEY_JSON: "${{ secrets.APP_ENGINE_DEPLOY_STAGING_SVCACCT_JSON }}"
          KEY_PASSPHRASE: "${{ secrets.APP_ENGINE_DEPLOY_STAGING_SVCACCT_PASSPHRASE }}"
          APPLICATION_CREDENTIALS: "${{ runner.temp }}/gcp.json"
          APPLICATION_CREDENTIALS_GPG: "${{ runner.temp }}/gcp.json.gpg"
      - run: gcloud info
      - shell: bash
        run: ./bin/deploy-staging.sh
        working-directory: server
      - name: Destroy GCP Credentials File
        run: rm $GOOGLE_APPLICATION_CREDENTIALS
        if: ${{ always() }}
        env:
          APPLICATION_CREDENTIALS: "${{ runner.temp }}/gcp.json"
      - name: Revoke GCP Credentials
        run: gcloud auth revoke
        if: ${{ always() }}
